### ISSUE TITLE
plot animation is flickering

### ISSUE THREAD

**Issue by hacknus** [massstab/ALIO#7]
On macOS the plot animation is flickering and showing the 0-line with no data a lot of the time. As I remember in previous versions this was not the case.

https://user-images.githubusercontent.com/33124824/225675867-5e27f9ff-cfc1-4ae5-850f-44bde6ce63f4.mov

**Comment by massstab** [comment]
There was no need for plt.draw() and plt.show(block=false). hacknus' pr #8 solved this issue. Also testet on windows. Thanks!
